version: '3.4'
services:
  app:
    build: .
    environment:
      ALPACA_KEY: somekey
      ALPACA_SECRET_KEY: somekey
      ALPACA_URL: https://paper-api.alpaca.markets
      REDDIT_CLIENT_ID: someid                  # Personal use script (14 characters).
      REDDIT_CLIENT_SECRET: somesecret          # Secret key (27 characters).
      REDDIT_USER_AGENT: someagent              # App name.
      REDDIT_USERNAME: someusername             # Reddit username.
      REDDIT_PASSWORD: somepassword             # Reddit password.
      FLASK_DEBUG: 1
      PYTHONHASHSEED: 0
    volumes:
      - .:/code
    ports:
      - "9656:9656"
